# Generated by Django 3.1.5 on 2021-02-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('publiser_name', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.CharField(max_length=255)),
                ('total_rating_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('total_rating_count', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
