# Generated by Django 3.1.5 on 2021-02-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
